CREATE TABLE GENEROS (
	ID_GENERO int NOT NULL IDENTITY(1,1),
	NOMBRE varchar(100) NOT NULL,
	CONSTRAINT PK_GENEROS_ID_GENERO PRIMARY KEY (ID_GENERO)
);

CREATE TABLE DIRECTORES (
	ID_DIRECTOR int NOT NULL IDENTITY(1,1),
	NOMBRE varchar(100) NOT NULL,
	CONSTRAINT PK_DIRECTORES_ID_DIRECTOR PRIMARY KEY (ID_DIRECTOR)
);

CREATE TABLE PELICULAS (
	ID_PELICULA int NOT NULL IDENTITY(1,1),
	TITULO varchar(200) NOT NULL,
	SINOPSIS varchar(8000),
	IMAGEN varchar(512),
	ANIO int,
	ID_DIRECTOR int NOT NULL,
	ID_GENERO int NOT NULL,
	CONSTRAINT PK_PELICULAS_ID_PELICULA PRIMARY KEY (ID_PELICULA),
	CONSTRAINT PELICULAS_DIRECTORES_FK FOREIGN KEY (ID_DIRECTOR) REFERENCES DIRECTORES(ID_DIRECTOR),
	CONSTRAINT PELICULAS_GENEROS_FK FOREIGN KEY (ID_GENERO) REFERENCES GENEROS(ID_GENERO)
);
